# Generated by Django 5.2 on 2025-06-08 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='batch_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='classroom',
            name='batch_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='standard',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
        migrations.AlterField(
            model_name='hall',
            name='floor',
            field=models.IntegerField(verbose_name='Floor'),
        ),
    ]
