# Generated by Django 5.2 on 2025-06-08 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomstudentaddable',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_room_students', to='students.student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='hall_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.hall', verbose_name='Hall'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.section'),
        ),
        migrations.AlterUniqueTogether(
            name='classroomstudentaddable',
            unique_together={('student', 'classroom')},
        ),
    ]
