# Generated by Django 5.2 on 2025-06-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_batch_end_classroom_batch_start_and_more'),
        ('students', '0002_student_group_alter_student_current_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
            options={
                'verbose_name': 'Student Batch',
                'verbose_name_plural': 'Student Batches',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoomStudentAddable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom_student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classroom.classroomstudent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_room_students', to='students.student')),
            ],
            options={
                'verbose_name': 'Class Room Student',
                'verbose_name_plural': 'Class Room Students',
                'unique_together': {('student', 'classroom_student')},
            },
        ),
    ]
