# Generated by Django 5.2 on 2025-06-08 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Until SSLC or SSC', max_length=255, verbose_name='Group SSC or SSLC and HSC')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Type subject name Eg. Tamil, English...', max_length=50, verbose_name='Subject Name')),
                ('description', models.TextField(help_text='Write few words about the subject', verbose_name='Subject Description')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_group', to='curriculum.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
