# Generated by Django 5.2 on 2025-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Until SSLC or SSC', max_length=255, verbose_name='Group SSC or SSLC and HSC'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Type subject name Eg. Tamil, English...', max_length=50, verbose_name='Subject Name'),
        ),
    ]
