# Generated by Django 5.2 on 2025-06-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_designation'),
        ('announcement', '0003_alter_staffannouncement_designation'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='joining_designation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.designation', verbose_name='Select Designation'),
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
