# Generated by Django 5.2 on 2025-06-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('last_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Classroom Announcement',
                'verbose_name_plural': 'Classroom Announcements',
            },
        ),
        migrations.CreateModel(
            name='StaffAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('last_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Staff Announcement',
                'verbose_name_plural': 'Staff Announcements',
            },
        ),
        migrations.CreateModel(
            name='StudentAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('last_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Student Announcement',
                'verbose_name_plural': 'Student Announcements',
            },
        ),
    ]
