# Generated by Django 5.2 on 2025-06-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0001_initial'),
        ('classroom', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomannouncement',
            name='classroom',
            field=models.ManyToManyField(to='classroom.classroom', verbose_name='Classroom'),
        ),
        migrations.AddField(
            model_name='staffannouncement',
            name='designation',
            field=models.ManyToManyField(to='staff.designation', verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='studentannouncement',
            name='students',
            field=models.ManyToManyField(to='students.student', verbose_name='Students'),
        ),
    ]
