# Generated by Django 5.2 on 2025-06-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_designation'),
        ('announcement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffannouncement',
            name='designation',
            field=models.ManyToManyField(to='administration.designation', verbose_name='Designation'),
        ),
    ]
