# Generated by Django 5.2 on 2025-06-08 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term')], default='First Term', max_length=255)),
                ('task_type', models.CharField(choices=[('assignment', 'Assignment'), ('homework', 'Homework'), ('project', 'Project'), ('deminar', 'Seminar')], default='Homework', max_length=255)),
                ('topic_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_marks', models.IntegerField(default=10)),
                ('last_date', models.DateField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_classroom', to='classroom.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='curriculum.subject')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'unique_together': {('subject',)},
            },
        ),
        migrations.CreateModel(
            name='IndividualTaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('mark', models.IntegerField(blank=True, default=0, null=True)),
                ('date_of_submission', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('late', 'Late'), ('not_submitted', 'Not Submitted')], default='Pending', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_task', to='students.student')),
                ('tast_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submission', to='task.task')),
            ],
            options={
                'verbose_name': 'Task submission list',
            },
        ),
    ]
